---
- include: redhat.yml
  when: ansible_distribution == 'RedHat'
  
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  
- include: amazon_linux.yml
  when: ansible_distribution == 'Amazon'